name: actions_on_main_branch
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:    
      - 'main'

jobs:
  job1:
    name: Merge Check
    runs-on: ubuntu-latest
    env:
      NAME_ADMIN: prashant753
    steps:
      - name: st1
        if: ${{ github.triggering_actor != env.NAME_ADMIN }}
        run: exit 1
      - name: st2
        if: ${{ github.triggering_actor == env.NAME_ADMIN }}
        run: echo "ok"
